[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=false)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyTitle("QuesterAssistant")]
[assembly: System.Reflection.AssemblyDescription("Expansion of Astral bot functions")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("Home")]
[assembly: System.Reflection.AssemblyProduct("QuesterAssistant")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2018 DartKotik")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("bda9e0e0-e277-4e37-85f7-78a40939901c")]
[assembly: System.Reflection.AssemblyFileVersion("1.3.1226.1141")]
[assembly: System.Reflection.AssemblyVersion("1.3.1.266")]